### ISSUE TITLE
output directory 

### ISSUE THREAD

**Issue by haroldgrosjean** [IAlibay/MDRestraintsGenerator#2]
Hi,

I am using your script using for inspiration ``BoreschRestraintGMX.py`` and it seems that the user has no control over the directory in which the files are created (i.e: they will always be created in the local directory).

I suggest the user can specify the output directory and the current directory would be the default option.

Thanks

**Comment by IAlibay** [comment]
Fixed via: https://github.com/bigginlab/MDRestraintsGenerator/pull/29
